### ISSUE TITLE
Bug in SBOX

### ISSUE THREAD

**Issue by nvandrueten** [tfpf/data-encryption-standard#2]
Found a bug in the coordy variable of the SBOX computation. Operator ^ is not a power operation, but a bitwise XOR. Therefore SBOX does not compute the correct output.

**Comment by tfpf** [comment]
It's interesting how that error crept in. I guess I didn't bother to check the code after getting the same decrypted output as the input.

Since the power function is used only with base 2, do you think it might be better to replace it with a left-shift operation?

**Comment by nvandrueten** [comment]
My power function is not a good idea. It is time-dependant on the input bits of the SBOX.

A left shift operation would look something like this: (1 << a) if I am correct.

**Comment by tfpf** [comment]
Yes, that's exactly what I meant by using a left-shift operation. With this change, the code seems to be working fine. I'll link https://github.com/tfpf/data-encryption-standard/pull/3 here.

**Comment by tfpf** [comment]
I'll merge this one. Feel free to create another pull for the restructing changes, if required.
